# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Max Wirt Maximum Website
description: > # this means to ignore newlines until "baseurl:"
  This is the personal website of Max Wirt.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://maxwirt.com" # the base hostname & protocol for your site
theme-color: "#26C6DA" # for head metadata and favicon


# Markdown settings
markdown: kramdown

# Sass settings
sass:
  add_charset: true
  sass_dir: assets/sass
  style: :compressed

# Build settings
exclude:
  - package.json
  - README.md
  - CNAME
  - assets/sass

# Plugin settings
plugins:
  - jekyll-feed
  - jekyll-sitemap

permalink: pretty